# Generated by Django 3.1.3 on 2020-11-18 15:45

from django.db import migrations, models
import newloader.models


class Migration(migrations.Migration):

    dependencies = [
        ('newloader', '0002_auto_20201118_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_files',
            name='data_file',
            field=models.FileField(upload_to=newloader.models.get_upload_file, verbose_name='Расположение'),
        ),
    ]
