# Generated by Django 3.1.3 on 2020-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newloader', '0003_auto_20201118_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_files',
            name='hash_file_ren',
            field=models.TextField(default='default title', max_length=1000, verbose_name='Хэш'),
        ),
    ]
